import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="border-b-2 h-10">
          <ul className="flex justify-around">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/posts">목록</Link>
            </li>
            <li>
              <Link href="/posts/write">글작성</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
